
apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-dashboard-config
  namespace: default
  labels:
    app: weather-dashboard
    project: devops-cse3253
data:
  FLASK_DEBUG: "false"
  PORT: "5000"
  DB_PATH: "/app/data/weather.db"